alias: "Christine has closed the door behind her after entering"
trigger:
  platform: state
  entity_id: input_boolean.front_door_closed
  to: 'on'
condition:
  - condition: state
    entity_id: input_select.christine_home_state
    state: Entering
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.christine_home_state
      option: Inside


