alias: 'Donnie opened door after getting home'
trigger:
  platform: state
  entity_id: sensor.front_door
  from: 'ON'
  to: 'OFF'
condition:
  condition: state
  entity_id: input_select.home_state
  state: Outside
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.home_state
      option: Entering
