alias: 'Donnie closed door and is inside'
trigger:
  platform: state
  entity_id: sensor.front_door
  from: 'OFF'
  to: 'ON'
condition:
  condition: state
  entity_id: input_select.home_state
  state: Entering
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.home_state
      option: Inside
