alias: 'React to pausing Plex on PS4'
trigger:
- platform: template
  value_template: "{% if is_state('media_player.plex_a9w8mh48b5u5b0xxxftt9q8w', 'paused') %}true{% endif %}"
- platform: template
  value_template: "{% if is_state('media_player.plex_a9w8mh48b5u5b0xxxftt9q8w', 'idle') %}true{% endif %}"
condition:
  condition: state
  entity_id: binary_sensor.dark_out
  state: 'on'
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.house_mode
      option: 'Intermission'
