alias: 'React to no more motion in bedroom'
trigger:
- platform: state
  entity_id: input_boolean.motion_detected
  to: 'off'
  for:
    minutes: 1
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.dark_out
      state: 'on'
    - condition: state
      entity_id: input_select.house_mode
      state: 'bedtime'
action:
  - service: light.turn_off
    entity_id: light.nightstand
