alias: "When input select is set to not home"
trigger:
  platform: state
  entity_id: input_select.home_state
  to: 'Not home'
action:
  - service: light.turn_off
    entity_id: group.all_lights
  - service: switch.turn_off
    entity_id: group.all_light_switches
