# Only during house mode: bedtime
# Only when dark out
alias: 'Turn on bedroom light when motion detected at bedtime'
trigger:
- platform: state
  entity_id: input_boolean.motion_detected
  to: 'on'
action:
  - service: light.turn_on
    data:
      entity_id: light.nightstand
      brightness: 50
      color_name: 'red'
