- action:
  - data:
      entity_id: group.bedroom
    service: homeassistant.turn_on
  alias: Enter Bedroom
  condition:
  - condition: state
    entity_id: input_boolean.beacon_lighting
    state: 'on'
  id: '1514958902643'
  trigger:
  - entity_id: device_tracker.donkawechico_heroqltevzw
    event: enter
    platform: zone
    zone: zone.bedroom
- action:
  - data:
      entity_id: group.bedroom
    service: homeassistant.turn_off
  alias: Exit Bedroom
  condition:
  - condition: state
    entity_id: input_boolean.beacon_lighting
    state: 'on'
  id: '1514959091997'
  trigger:
  - entity_id: device_tracker.donkawechico_heroqltevzw
    event: leave
    platform: zone
    zone: zone.bedroom
- action:
  - data:
      entity_id: group.living_room
    service: homeassistant.turn_on
  alias: Enter Livingroom
  condition:
  - condition: state
    entity_id: input_boolean.beacon_lighting
    state: 'on'
  id: '1514959163860'
  trigger:
  - entity_id: device_tracker.donkawechico_heroqltevzw
    event: enter
    platform: zone
    zone: zone.livingroom
- action:
  - data:
      entity_id: group.living_room
    service: homeassistant.turn_off
  alias: Exit Livingroom
  condition:
  - condition: state
    entity_id: input_boolean.beacon_lighting
    state: 'on'
  id: '1514959219659'
  trigger:
  - entity_id: device_tracker.donkawechico_heroqltevzw
    event: leave
    platform: zone
    zone: zone.livingroom
- action:
  - data:
      entity_id: group.entry
    service: homeassistant.turn_on
  - data:
      entity_id: group.shop
    service: homeassistant.turn_on
  alias: Enter Entryway
  condition:
  - condition: state
    entity_id: input_boolean.beacon_lighting
    state: 'on'
  id: '1514959301958'
  trigger:
  - entity_id: device_tracker.donkawechico_heroqltevzw
    event: enter
    platform: zone
    zone: zone.entry
- action:
  - data:
      entity_id: group.entry
    service: homeassistant.turn_off
  - data:
      entity_id: group.shop
    service: homeassistant.turn_off
  alias: Exit Entryway
  condition:
  - condition: state
    entity_id: input_boolean.beacon_lighting
    state: 'on'
  id: '1514959381983'
  trigger:
  - entity_id: device_tracker.donkawechico_heroqltevzw
    event: leave
    platform: zone
    zone: zone.entry
