- id: '1521615321464'
  alias: Turn on heater at 6:45 if Christine is there
  trigger:
  - at: 06:45:00
    platform: time
  condition:
  - below: '73'
    condition: numeric_state
    entity_id: sensor.aeotech_multisensor_6_temperature
  - condition: state
    entity_id: device_tracker.christine_phone
    state: home
  action:
  - service: script.turn_on_heater
- id: '1521615521241'
  alias: Turn off heater at 8
  trigger:
  - at: 08:00:00
    platform: time
  condition: []
  action:
  - service: script.turn_off_heater
- id: '1531621091643'
  alias: Turn Off AC on restart (ensures correct bool)
  initial_state: 'on'
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      entity_id: script.turn_off_ac
    service: script.turn_on
- id: '1537471675803'
  alias: Set Climate 'Away Mode' when not at home
  trigger:
  - entity_id: binary_sensor.someone_home
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: climate.living_room
      preset_mode: away
    service: climate.set_preset_mode
- id: '1537496116823'
  alias: Turn on climate control when someone is home
  trigger:
  - entity_id: binary_sensor.someone_home
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: climate.living_room
      preset_mode: none
    service: climate.set_preset_mode
- id: '1564419516085'
  alias: Notify Me when AC state changes
  trigger:
  - entity_id: input_boolean.ac_on
    platform: state
  condition: []
  action:
  - data:
      message: The AC is {{ states.input_boolean.ac_on.state }}
    service: notify.telegram
- id: '1564422413764'
  alias: Notify me when at donnie home state changes
  trigger:
  - entity_id: binary_sensor.donnie_home
    platform: state
  condition: []
  action:
  - data:
      message: Donnie is {% if is_state('binary_sensor.donnie_home', 'off') %}not
        home{% else %}home{% endif %}
    service: notify.telegram
