- id: '1521615521241'
  alias: Turn off HVAC at noon
  trigger:
  - at: '12:00:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: script.turn_off_hvac
    service: script.turn_on
- id: '1531621091643'
  alias: Turn Off AC on restart (ensures correct bool)
  initial_state: 'on'
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      entity_id: script.turn_off_hvac
    service: script.turn_on
- id: '1537471675803'
  alias: Set Climate 'Away Mode' when not at home
  trigger:
  - entity_id: binary_sensor.someone_home
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: climate.thermostat
      preset_mode: away
    service: climate.set_preset_mode
- id: '1537496116823'
  alias: Turn on climate control when someone is home
  trigger:
  - entity_id: binary_sensor.someone_home
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: climate.thermostat
      preset_mode: none
    service: climate.set_preset_mode
  - data:
      entity_id: script.turn_on_climate_control
    service: script.turn_on
- id: '1564422413764'
  alias: Donnie left or arrived at home. Confirm
  trigger:
  - entity_id: binary_sensor.donnie_home
    platform: state
  condition: []
  action:
  - data:
      data:
        actions:
        - action: donnie_away
          title: AWAY
        - action: donnie_home
          title: HOME
      message: Donnie is {% if is_state('binary_sensor.donnie_home', 'off') %}AWAY{%
        else %}HOME{% endif %}. Confirm?
    service: notify.mobile_app_donnie
- id: '1565131144880'
  alias: '[MOTION][NOTIFY] Motion In Empty House'
  trigger:
  - entity_id: binary_sensor.motion_detected_anywhere
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.someone_home
    state: 'off'
  action:
  - data:
      data:
        actions:
        - action: guest_mode
          title: GUEST
        - action: raise_alarm
          title: INTRUDER
        - action: donnie_home
          title: ME
        - action: christine_home
          title: CHRISTINE
        - action: nothing
          title: ITS FINE
      message: Motion detected, but you guys are away. Who is it?
      title: ALARM
    service: notify.mobile_app_donnie
- id: '1565832071987'
  alias: Take Photo When Door Opens
  trigger:
  - entity_id: sensor.front_door
    platform: state
    to: OPEN
  condition: []
  action:
  - data:
      entity_id: script.take_photo_livingroom
    service: script.turn_on
- id: '1578336447908'
  alias: Notify me if door opens and no one is home
  description: ''
  trigger:
  - entity_id: sensor.front_door
    from: CLOSED
    platform: state
    to: OPEN
  condition:
  - condition: state
    entity_id: binary_sensor.someone_home
    state: 'off'
  action:
  - data:
      message: Door opened, but no one is home. Sending photo in 10 seconds.
      target: -307549115
    service: notify.mobile_app_donnie
  - data:
      message: Door opened, but no one is home. Sending photo in 10 seconds.
      target: -307549115
    service: notify.mobile_app_christine
  - data:
      filename: var/tmp/outdoor_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg
    entity_id: camera.outdoor
    service: camera.snapshot
  - data:
      filename: var/tmp/indoor_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg
    entity_id: camera.indoor
    service: camera.snapshot
  - delay: 00:00:10
- id: '1578513106734'
  alias: '[MOTION][RECORD] five-second video'
  description: ''
  trigger:
  - entity_id: binary_sensor.motion_detected_anywhere
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.someone_home
    state: 'off'
  action:
  - service: shell_command.record_raspicam_minute
- id: '1579195169252'
  alias: '[CAR][FUEL][NOTIFY] Low'
  description: ''
  trigger:
  - entity_id: device_tracker.2012_mazda_mazda3
    platform: state
  - event_data:
      type: ignition:on
      vehicle:
        id: C_38ff41f78ad35e19
    event_type: automatic_update
    platform: event
  condition:
  - condition: template
    value_template: '{{ state_attr("device_tracker.2012_mazda_mazda3", "fuel_level")
      < 20 }}'
  action:
  - data_template:
      message: Vee needs gas! Dilythium chambers running at {{ state_attr("device_tracker.2012_mazda_mazda3",
        "fuel_level") }}%
    service: notify.mobile_app_donnie
  - data_template:
      message: Vee needs gas! Dilythium chambers running at {{ state_attr("device_tracker.2012_mazda_mazda3",
        "fuel_level") }}%
    service: notify.mobile_app_christine
- id: '1579402567251'
  alias: '[LIGHT][SHADES] Close when it''s too bright'
  description: ''
  trigger:
  - above: '300'
    entity_id: sensor.multisensor_living_room_luminance
    platform: numeric_state
  condition:
  - condition: template
    value_template: '{{ state_attr(''automation.light_shades_close_when_it_s_too_bright'',''last_triggered'').astimezone().day
      != now().day }}'
  action:
  - entity_id: cover.shades
    service: cover.close_cover
- id: '1580018856284'
  alias: When AC or Heater go on, HVAC is on
  description: ''
  trigger:
  - entity_id: input_boolean.ac_on
    platform: state
    to: 'on'
  condition: []
  action:
  - entity_id: input_boolean.hvac_on
    service: input_boolean.turn_on
- id: '1580018930733'
  alias: When AC is on, Heater is off
  description: ''
  trigger:
  - entity_id: input_boolean.ac_on
    platform: state
    to: 'on'
  condition: []
  action:
  - entity_id: input_boolean.heater_on
    service: input_boolean.turn_off
- id: '1580018967885'
  alias: When Heater is on, AC is off
  description: ''
  trigger:
  - entity_id: input_boolean.heater_on
    platform: state
    to: 'on'
  condition: []
  action:
  - entity_id: input_boolean.ac_on
    service: input_boolean.turn_off
- id: '1580347475732'
  alias: Notify me when christine leaves work
  description: ''
  trigger:
  - entity_id: person.donnie
    platform: state
  condition:
  - condition: template
    value_template: "{{ true or ( trigger.to_state.state is not none\n    and trigger.from_state.state\
      \ is not none\n    and trigger.to_state.state != trigger.from_state.state) }}\n"
  action:
  - service_template: script.notify_presence
    data_template:
      trigger: Presence tracking
      entityid: '{{trigger.entity_id}}'
      tostate: '{{trigger.to_state.state}}'
      fromstate: '{{trigger.from_state.state}}'
- id: '1581495559638'
  alias: Turn on kitchen lights when motion detected
  description: ''
  trigger:
  - entity_id: input_boolean.motion_kitchen
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.dark_out
    state: 'on'
  action:
  - entity_id: light.kitchen_lights
    service: light.turn_on
- id: '1581495869865'
  alias: Turn off kitchen lights when no motion
  description: ''
  trigger:
  - entity_id: input_boolean.motion_kitchen
    platform: state
    to: 'off'
  condition: []
  action:
  - entity_id: light.kitchen_lights
    service: light.turn_off
- id: '1581554837241'
  alias: Set theme at startup
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - service: script.set_theme_ios_dark_mode
- id: '1581820299476'
  alias: Nest dashboard every 5 minutes
  description: ''
  trigger:
  - minutes: /1
    platform: time_pattern
  condition: []
  action:
  - data:
      entity_id: media_player.nest_hub
      view_path: nest_hub
    entity_id: media_player.nest_hub
    service: cast.show_lovelace_view
- id: '1582848642973'
  alias: Raise shades at 1pm
  description: ''
  trigger:
  - at: '13:00:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: cover.shades
    service: cover.open_cover
- id: '1583031719997'
  alias: Turn on the auto-kitchen-light feature when dinner projector set
  description: ''
  trigger:
  - event_data:
      domain: scene
      entity_id:
      - scene.dinner_projector
      service: turn_on
    event_type: call_service
    platform: event
  condition: []
  action:
  - data: {}
    entity_id: automation.turn_off_kitchen_lights_when_no_motion
    service: automation.turn_on
  - data: {}
    entity_id: automation.turn_on_kitchen_lights_when_motion_detected
    service: automation.turn_on
- id: '1583292018699'
  alias: Remote increases house lights
  description: ''
  trigger:
  - entity_id: remote.hue_dimmer_switch
    platform: state
  condition:
  - condition: template
    value_template: '{{ is_state("remote.hue_dimmer_switch", "2_click_up") }}'
  action:
  - data:
      brightness_step_pct: 20
    entity_id: light.all_color_lights
    service: light.turn_on
- id: '1583293095094'
  alias: Remote decreases house lights
  description: ''
  trigger:
  - entity_id: remote.hue_dimmer_switch
    platform: state
  condition:
  - condition: template
    value_template: '{{ is_state("remote.hue_dimmer_switch", "3_click_up") }}'
  action:
  - data:
      brightness_step_pct: -20
    entity_id: light.all_color_lights
    service: light.turn_on
- id: '1583293401610'
  alias: Remote turns on house lights
  description: ''
  trigger:
  - entity_id: remote.hue_dimmer_switch
    platform: state
    to: 1_click
  - entity_id: remote.hue_dimmer_switch
    platform: state
    to: 1_click_up
  condition: []
  action:
  - data: {}
    entity_id: light.house_lights
    service: light.turn_on
- id: '1583293503401'
  alias: Remote turns off house lights
  description: ''
  trigger:
  - entity_id: remote.hue_dimmer_switch
    platform: state
    to: 4_click
  - entity_id: remote.hue_dimmer_switch
    platform: state
    to: 4_click_up
  condition: []
  action:
  - data: {}
    entity_id: light.house_lights
    service: light.turn_off
- id: '1583443372103'
  alias: Remote sets maximum brightness
  description: ''
  trigger:
  - entity_id: remote.hue_dimmer_switch
    platform: state
    to: 2_hold
  - entity_id: remote.hue_dimmer_switch
    platform: state
    to: 2_hold_up
  condition: []
  action:
  - data:
      brightness_pct: 100
    entity_id: light.all_color_lights
    service: light.turn_on
- id: '1583443583862'
  alias: Remote sets minimum brightness
  description: ''
  trigger:
  - entity_id: remote.hue_dimmer_switch
    platform: state
    to: 3_hold
  - entity_id: remote.hue_dimmer_switch
    platform: state
    to: 3_hold_up
  condition: []
  action:
  - data:
      brightness_pct: 10
    entity_id: light.all_color_lights
    service: light.turn_on
- id: '1583794486051'
  alias: Alexa tells me when door is open
  description: ''
  trigger:
  - entity_id: sensor.front_door
    for: 00:00:30
    platform: state
    to: OPEN
  condition: []
  action:
  - data:
      message: The door is open
      target: media_player.entryway
    service: script.1583791558443
