- platform: mqtt
  name: "Accent Lights"
  state_topic: "stat/accent/POWER"
  command_topic: "cmnd/accent/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Pool Table Light"
  state_topic: "stat/pooltablelight/POWER"
  command_topic: "cmnd/pooltablelight/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Macrame Light"
  state_topic: "stat/macramelight/POWER"
  command_topic: "cmnd/macramelight/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Music Light"
  state_topic: "stat/musiclight/POWER"
  command_topic: "cmnd/musiclight/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Water Light"
  state_topic: "stat/waterlight/POWER"
  command_topic: "cmnd/waterlight/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Is Kitchen Strip On"
  state_topic: "hass/light/kitchen/strip"
  command_topic: "hass/light/kitchen/strip"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Star Field"
  state_topic: "stat/starfield/POWER"
  command_topic: "cmnd/starfield/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: command_line
  switches:
    # Relies on https://github.com/skorokithakis/catt
    suncast_fireplace:
      command_on: "/usr/local/bin/catt cast 'https://www.youtube.com/watch?v=6RoTpvA9MSw'"
      command_off: "/usr/local/bin/catt stop"
- platform: template
  switches:
    air_conditioner:
      value_template: "{{ is_state('input_boolean.ac_on','on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_ac
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_ac
    heater:
      value_template: "{{ is_state('input_boolean.heater_on','on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_heater
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_heater
    television:
      value_template: "{{ is_state('input_boolean.tv_on','on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_tv
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_tv
    shop_tv:
      value_template: "{{ is_state('input_boolean.shop_tv_on','on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_shop_tv
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_shop_tv
    playstation:
      value_template: "{{ is_state('input_boolean.playstation_on','on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_playstation
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_playstation
    # plex:
    #   value_template: "{{ is_state_attr('media_player.ps4_waker','source','Plex') }}"
    #   turn_on:
    #     service: script.turn_on
    #     entity_id: script.turn_on_ps4_waker_plex
    #   turn_off:
    #     service: script.turn_on
    #     entity_id: script.turn_off_ps4_waker_plex    
    chromecast:
      value_template: "{{ is_state('input_boolean.chromecast_on','on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_chromecast
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_chromecast
    projector:
      value_template: "{{ is_state('input_boolean.projector_on','on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_projector
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_projector
    sun_projector:
      value_template: "{{ is_state('input_boolean.sun_projector_on','on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_sun_projector
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_sun_projector
    bedtime_projector:
      value_template: "{{ is_state('input_boolean.bedtime_projector','on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_bedtime_projector
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_bedtime_projector
    climate_control:
      value_template: "{{ states.climate.thermostat.attributes.hvac_action != 'off' }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_climate_control
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_climate_control
