- platform: mqtt
  name: "Accent Lights"
  state_topic: "stat/accent/POWER"
  command_topic: "cmnd/accent/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Pool Table Light"
  state_topic: "stat/pooltablelight/POWER"
  command_topic: "cmnd/pooltablelight/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Macrame Light"
  state_topic: "stat/macramelight/POWER"
  command_topic: "cmnd/macramelight/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Music Light"
  state_topic: "stat/musiclight/POWER"
  command_topic: "cmnd/musiclight/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Ceiling Lights"
  state_topic: "stat/ceiling_lights/POWER"
  command_topic: "cmnd/ceiling_lights/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Is Kitchen Strip On"
  state_topic: "hass/light/kitchen/strip"
  command_topic: "hass/light/kitchen/strip"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Star Field"
  state_topic: "stat/starfield/POWER"
  command_topic: "cmnd/starfield/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: command_line
  switches:
    # Relies on https://github.com/skorokithakis/catt
    suncast_fireplace:
      command_on: "/usr/local/bin/catt cast 'https://www.youtube.com/watch?v=6RoTpvA9MSw'"
      command_off: "/usr/local/bin/catt stop"
- platform: template
  switches:
    air_conditioner:
      friendly_name: "Air Conditioner"
      value_template: "{{ is_state('input_boolean.ac_on','on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_ac
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_hvac
    heater:
      friendly_name: "Heater"
      value_template: "{{ is_state('input_boolean.heater_on','on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_heater
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_hvac
    television:
      friendly_name: "TV"
      value_template: "{{ is_state('input_boolean.tv_on','on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_tv
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_tv
    shop_tv:
      friendly_name: "Shop TV"
      value_template: "{{ is_state('input_boolean.shop_tv_on','on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_shop_tv
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_shop_tv
    playstation:
      friendly_name: "Playstation"
      value_template: "{{ is_state('input_boolean.is_playstation_on','on') }}"
 # Change this to use unifi TX stats (since ps4 is prone to shutting down suddenly)
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_playstation
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_playstation
    chromecast:
      friendly_name: "Chromecast"
      value_template: "{{ is_state('input_boolean.chromecast_on','on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_chromecast
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_chromecast
    projector:
      friendly_name: "Projector"
      value_template: "{{ is_state('input_boolean.projector_on','on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_projector
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_projector
    sun_projector:
      friendly_name: "Sun Projector"
      value_template: "{{ is_state('input_boolean.sun_projector_on','on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_sun_projector
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_sun_projector
    bedtime_projector:
      friendly_name: "Bedtime Projector"
      value_template: "{{ is_state('input_boolean.bedtime_projector','on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_bedtime_projector
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_bedtime_projector
    climate_control:
      friendly_name: "Climate Control"
      value_template: "{{ not is_state('climate.thermostat.attributes.hvac_action', 'off') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_climate_control
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_climate_control
#    hvac_auto_select:
#      value_template: "{{ states.climate.thermostat.attributes.hvac_action != 'off' }}"
#      turn_on:
#        service: climate.set_hvac_mode
#        data_template:
#          entity_id: climate.thermostat
#          hvac_mode: '{{ "cool" }}'
#      turn_off:
#        service: script.turn_on
#        entity_id: script.turn_off_hvac
