$(function(){ //DOM Ready

    function navigate(url)
    {
        window.location.href = url;
    }

    $(document).attr("title", "Main Panel");
    content_width = (120 + 5) * 8 + 5
    $('.gridster').width(content_width)
    $(".gridster ul").gridster({
        widget_margins: [5, 5],
        widget_base_dimensions: [120, 120],
        avoid_overlapped_widgets: true,
        max_rows: 15,
        max_size_x: 8,
        shift_widgets_up: false
    }).data('gridster').disable();
    
    // Add Widgets

    var gridster = $(".gridster ul").gridster().data('gridster');
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseclock-default-clock-clock" id="default-clock-clock"><h1 class="date"data-bind="text: date, attr: {style: date_style}"></h1><h2 class="time" data-bind="text: time, attr: {style: time_style}"></h2></div></li>', 2, 2, 1, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basedisplay-default-label-sensors" id="default-label-sensors"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><div class="valueunit"><h2 class="value" data-bind="html: value, attr:{ style: value_style}"></h2><p class="unit" data-bind="html: unit, attr:{ style: unit_style}"></p></div><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 6, 1, 3, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basedisplay-default-sensor-front-door" id="default-sensor-front-door"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><div class="valueunit"><h2 class="value" data-bind="html: value, attr:{ style: value_style}"></h2><p class="unit" data-bind="html: unit, attr:{ style: unit_style}"></p></div><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 3, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-dark-outside-sensor" id="default-dark-outside-sensor"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 4, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-donnie-presence" id="default-donnie-presence"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 5, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-christine-presence" id="default-christine-presence"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 6, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basedisplay-default-pir-1" id="default-pir-1"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><div class="valueunit"><h2 class="value" data-bind="html: value, attr:{ style: value_style}"></h2><p class="unit" data-bind="html: unit, attr:{ style: unit_style}"></p></div><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 7, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basedisplay-default-label-rooms" id="default-label-rooms"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><div class="valueunit"><h2 class="value" data-bind="html: value, attr:{ style: value_style}"></h2><p class="unit" data-bind="html: unit, attr:{ style: unit_style}"></p></div><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 3, 1, 1, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basedisplay-default-label-scenes" id="default-label-scenes"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><div class="valueunit"><h2 class="value" data-bind="html: value, attr:{ style: value_style}"></h2><p class="unit" data-bind="html: unit, attr:{ style: unit_style}"></p></div><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 2, 1, 4, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basedisplay-default-label-sync" id="default-label-sync"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><div class="valueunit"><h2 class="value" data-bind="html: value, attr:{ style: value_style}"></h2><p class="unit" data-bind="html: unit, attr:{ style: unit_style}"></p></div><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 2, 1, 6, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-house-lights" id="default-house-lights"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 1, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-livingroom" id="default-livingroom"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 2, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-kitchen" id="default-kitchen"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 3, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-underwater-scene" id="default-underwater-scene"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 4, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-darkness-scene" id="default-darkness-scene"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 5, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-kitchen-strip" id="default-kitchen-strip"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 6, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-sync-kitchen-strip" id="default-sync-kitchen-strip"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 7, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-shop" id="default-shop"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 1, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-bedroom" id="default-bedroom"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 2, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-theater-scene" id="default-theater-scene"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 4, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-warm-scene" id="default-warm-scene"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 5, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basedisplay-default-label-state" id="default-label-state"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><div class="valueunit"><h2 class="value" data-bind="html: value, attr:{ style: value_style}"></h2><p class="unit" data-bind="html: unit, attr:{ style: unit_style}"></p></div><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 4, 1, 5, 6)
    
    
    
    var widgets = {}
    // Initialize Widgets
    
        widgets["default-clock-clock"] = new baseclock("default-clock-clock", "http://dk.servebeer.com:5050", "default", {'css': {}, 'icons': [], 'use_comma': 0, 'fields': {'date': '', 'time': ''}, 'title_is_friendly_name': 1, 'widget_type': 'baseclock', 'entity': 'clock.clock', 'precision': 1, 'static_css': {'time_style': 'color: #aa00ff;', 'widget_style': 'background-color: #444;', 'date_style': 'color: #fff;'}, 'use_hass_icon': 1, 'static_icons': []})
    
        widgets["default-label-sensors"] = new basedisplay("default-label-sensors", "http://dk.servebeer.com:5050", "default", {'css': {}, 'icons': [], 'use_comma': 0, 'fields': {'value': 'Sensors', 'unit': '', 'state_text': '', 'title2': '', 'title': ''}, 'widget_type': 'basedisplay', 'precision': 1, 'static_icons': [], 'use_hass_icon': 1, 'static_css': {'widget_style': 'background-color: #444;', 'unit_style': '', 'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'value_style': 'color: #fff;'}})
    
        widgets["default-sensor-front-door"] = new basedisplay("default-sensor-front-door", "http://dk.servebeer.com:5050", "default", {'use_comma': 0, 'title_is_friendly_name': 1, 'fields': {'value': '', 'unit': '', 'state_text': '', 'title2': '', 'title': ''}, 'css': {'unit_style': 'color: #00aaff;font-size: 100%;', 'text_style': 'color: #fff;font-size: 100%;', 'value_style': 'color: #00aaff;font-size: 250%;'}, 'entity': 'sensor.front_door', 'precision': 1, 'icons': [], 'sub_entity': '', 'widget_type': 'basedisplay', 'static_css': {'widget_style': 'background-color: #444;', 'unit_style': '', 'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': '', 'value_style': ''}, 'use_hass_icon': 1, 'static_icons': []})
    
        widgets["default-dark-outside-sensor"] = new baseswitch("default-dark-outside-sensor", "http://dk.servebeer.com:5050", "default", {'use_comma': 0, 'state_active': 'on', 'css': {'icon_style_inactive': 'color: #888;', 'icon_style_active': 'color: #ff0055;'}, 'entity': 'binary_sensor.dark_out', 'precision': 1, 'enable': 0, 'icons': {'icon_off': 'mdi-weather-sunny', 'icon_on': 'mdi-weather-night'}, 'static_css': {'widget_style': 'background-color: #444;', 'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;'}, 'fields': {'icon_style': '', 'state_text': '', 'title2': '', 'title': 'Dark Outside', 'icon': ''}, 'widget_type': 'baseswitch', 'icon_off': 'mdi-weather-sunny', 'state_inactive': 'off', 'icon_on': 'mdi-weather-night', 'use_hass_icon': 1, 'static_icons': []})
    
        widgets["default-donnie-presence"] = new baseswitch("default-donnie-presence", "http://dk.servebeer.com:5050", "default", {'state_text': 1, 'post_service_active': {'service': 'device_tracker/see', 'dev_id': 'donkawechico_heroqltevzw', 'location_name': 'home'}, 'state_active': 'home', 'css': {'icon_style_inactive': 'color: #888;', 'icon_style_active': 'color: #aaff00;'}, 'entity': 'device_tracker.donkawechico_heroqltevzw', 'precision': 1, 'state_map': {'not_home': 'AWAY', 'home': 'HOME'}, 'enable': 0, 'icons': {'icon_off': 'fa-user', 'icon_on': 'fa-user'}, 'fields': {'icon_style': '', 'state_text': '', 'title2': '', 'title': 'Donnie', 'icon': ''}, 'widget_type': 'baseswitch', 'use_comma': 0, 'state_inactive': 'not_home', 'static_css': {'widget_style': 'background-color: #444;', 'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;'}, 'post_service_inactive': {'service': 'device_tracker/see', 'dev_id': 'donkawechico_heroqltevzw', 'location_name': 'not_home'}, 'use_hass_icon': 1, 'static_icons': []})
    
        widgets["default-christine-presence"] = new baseswitch("default-christine-presence", "http://dk.servebeer.com:5050", "default", {'state_text': 1, 'post_service_active': {'service': 'device_tracker/see', 'dev_id': 'android2426752091905543', 'location_name': 'home'}, 'state_active': 'home', 'css': {'icon_style_inactive': 'color: #888;', 'icon_style_active': 'color: #aaff00;'}, 'entity': 'device_tracker.android2426752091905543', 'precision': 1, 'title_style': 'color: red;', 'state_map': {'not_home': 'AWAY', 'home': 'HOME'}, 'enable': 0, 'icons': {'icon_off': 'fa-user', 'icon_on': 'fa-user'}, 'fields': {'icon_style': '', 'state_text': '', 'title2': '', 'title': 'Christine', 'icon': ''}, 'widget_type': 'baseswitch', 'use_comma': 0, 'state_inactive': 'not_home', 'static_css': {'widget_style': 'background-color: #444;', 'title_style': 'color: red;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;'}, 'post_service_inactive': {'service': 'device_tracker/see', 'dev_id': 'android2426752091905543', 'location_name': 'not_home'}, 'use_hass_icon': 1, 'static_icons': []})
    
        widgets["default-pir-1"] = new basedisplay("default-pir-1", "http://dk.servebeer.com:5050", "default", {'widget_type': 'basedisplay', 'icons': [], 'use_comma': 0, 'sub_entity': '', 'fields': {'value': '', 'unit': '', 'state_text': '', 'title2': '', 'title': 'House Movement'}, 'css': {'unit_style': 'color: #00aaff;font-size: 100%;', 'text_style': 'color: #fff;font-size: 100%;', 'value_style': 'color: #00aaff;font-size: 250%;'}, 'entity': 'sensor.motion_sensor', 'precision': 1, 'static_icons': [], 'use_hass_icon': 1, 'static_css': {'widget_style': 'background-color: #444;', 'unit_style': '', 'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': '', 'value_style': ''}})
    
        widgets["default-label-rooms"] = new basedisplay("default-label-rooms", "http://dk.servebeer.com:5050", "default", {'css': {}, 'icons': [], 'use_comma': 0, 'fields': {'value': 'Room Lights', 'unit': '', 'state_text': '', 'title2': '', 'title': ''}, 'widget_type': 'basedisplay', 'precision': 1, 'static_icons': [], 'use_hass_icon': 1, 'static_css': {'widget_style': 'background-color: #444;', 'unit_style': '', 'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'value_style': 'color: #fff;'}})
    
        widgets["default-label-scenes"] = new basedisplay("default-label-scenes", "http://dk.servebeer.com:5050", "default", {'css': {}, 'icons': [], 'use_comma': 0, 'fields': {'value': 'Scenes', 'unit': '', 'state_text': '', 'title2': '', 'title': ''}, 'widget_type': 'basedisplay', 'precision': 1, 'static_icons': [], 'use_hass_icon': 1, 'static_css': {'widget_style': 'background-color: #444;', 'unit_style': '', 'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'value_style': 'color: #fff;'}})
    
        widgets["default-label-sync"] = new basedisplay("default-label-sync", "http://dk.servebeer.com:5050", "default", {'css': {}, 'icons': [], 'use_comma': 0, 'fields': {'value': 'Sync', 'unit': '', 'state_text': '', 'title2': '', 'title': ''}, 'widget_type': 'basedisplay', 'precision': 1, 'static_icons': [], 'use_hass_icon': 1, 'static_css': {'widget_style': 'background-color: #444;', 'unit_style': '', 'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'value_style': 'color: #fff;'}})
    
        widgets["default-house-lights"] = new baselight("default-house-lights", "http://dk.servebeer.com:5050", "default", {'use_comma': 0, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'group.house_lights'}, 'css': {'icon_style_inactive': 'color: #888;', 'icon_style_active': 'color: #aaff00;'}, 'entity': 'group.house_lights', 'precision': 1, 'icons': {'icon_off': 'mdi-home', 'icon_on': 'mdi-home'}, 'static_css': {'level_up_style': 'color: #888;', 'level_style': 'color: #fff;', 'widget_style': 'background-color: #444;', 'level_down_style': 'color: #888;', 'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'state_text_style': 'color: #fff;'}, 'fields': {'units': '%', 'state_text': '', 'title2': '', 'level': '', 'icon_style': '', 'title': 'House', 'icon': ''}, 'widget_type': 'baselight', 'icon_off': 'mdi-home', 'icon_on': 'mdi-home', 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'group.house_lights'}, 'use_hass_icon': 1, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}})
    
        widgets["default-livingroom"] = new baselight("default-livingroom", "http://dk.servebeer.com:5050", "default", {'use_comma': 0, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'group.living_room'}, 'css': {'icon_style_inactive': 'color: #888;', 'icon_style_active': 'color: #aaff00;'}, 'entity': 'group.living_room', 'precision': 1, 'icons': {'icon_off': 'mdi-sofa', 'icon_on': 'mdi-sofa'}, 'static_css': {'level_up_style': 'color: #888;', 'level_style': 'color: #fff;', 'widget_style': 'background-color: #444;', 'level_down_style': 'color: #888;', 'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'state_text_style': 'color: #fff;'}, 'fields': {'units': '%', 'state_text': '', 'title2': '', 'level': '', 'icon_style': '', 'title': 'Livingroom', 'icon': ''}, 'widget_type': 'baselight', 'icon_off': 'mdi-sofa', 'icon_on': 'mdi-sofa', 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'group.living_room'}, 'use_hass_icon': 1, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}})
    
        widgets["default-kitchen"] = new baselight("default-kitchen", "http://dk.servebeer.com:5050", "default", {'use_comma': 0, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'group.kitchen'}, 'css': {'icon_style_inactive': 'color: #888;', 'icon_style_active': 'color: #aaff00;'}, 'entity': 'group.kitchen', 'precision': 1, 'icons': {'icon_off': 'mdi-fridge', 'icon_on': 'mdi-fridge'}, 'static_css': {'level_up_style': 'color: #888;', 'level_style': 'color: #fff;', 'widget_style': 'background-color: #444;', 'level_down_style': 'color: #888;', 'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'state_text_style': 'color: #fff;'}, 'fields': {'units': '%', 'state_text': '', 'title2': '', 'level': '', 'icon_style': '', 'title': 'Kitchen', 'icon': ''}, 'widget_type': 'baselight', 'icon_off': 'mdi-fridge', 'icon_on': 'mdi-fridge', 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'group.kitchen'}, 'use_hass_icon': 1, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}})
    
        widgets["default-underwater-scene"] = new baseswitch("default-underwater-scene", "http://dk.servebeer.com:5050", "default", {'ignore_state': 1, 'use_comma': 0, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'scene.underwater'}, 'state_active': 'stillscening', 'css': {'icon_style_inactive': 'color: #888;', 'icon_style_active': 'color: #aaff00;'}, 'entity': 'scene.underwater', 'precision': 1, 'title_style': 'color: #138D75;font-weight:bold;', 'static_icons': [], 'momentary': 1000, 'enable': 1, 'icons': {'icon_off': 'mdi-fish', 'icon_on': 'mdi-fish'}, 'static_css': {'widget_style': 'background-color: #AED6F1;', 'title_style': 'color: #138D75;font-weight:bold;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;'}, 'fields': {'icon_style': '', 'state_text': '', 'title2': '', 'title': 'Underwater', 'icon': ''}, 'widget_type': 'baseswitch', 'icon_off': 'mdi-fish', 'state_inactive': 'scening', 'icon_on': 'mdi-fish', 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'scene.underwater'}, 'use_hass_icon': 1, 'widget_style': 'background-color: #AED6F1;'})
    
        widgets["default-darkness-scene"] = new baseswitch("default-darkness-scene", "http://dk.servebeer.com:5050", "default", {'ignore_state': 1, 'use_comma': 0, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'scene.darkness'}, 'state_active': 'stillscening', 'css': {'icon_style_inactive': 'color: #888;', 'icon_style_active': 'color: #aaff00;'}, 'entity': 'scene.darkness', 'precision': 1, 'static_icons': [], 'momentary': 1000, 'enable': 1, 'icons': {'icon_off': 'mdi-lightbulb-on', 'icon_on': 'mdi-lightbulb'}, 'static_css': {'widget_style': 'background-color: #8E44AD;', 'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;'}, 'fields': {'icon_style': '', 'state_text': '', 'title2': '', 'title': 'Lights Off', 'icon': ''}, 'widget_type': 'baseswitch', 'icon_off': 'mdi-lightbulb-on', 'state_inactive': 'scening', 'icon_on': 'mdi-lightbulb', 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'scene.darkness'}, 'use_hass_icon': 1, 'widget_style': 'background-color: #8E44AD;'})
    
        widgets["default-kitchen-strip"] = new baselight("default-kitchen-strip", "http://dk.servebeer.com:5050", "default", {'use_comma': 0, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.kitchen_strip'}, 'css': {'icon_style_inactive': 'color: #888;', 'icon_style_active': 'color: #aaff00;'}, 'entity': 'light.kitchen_strip', 'precision': 1, 'icons': {'icon_off': 'fa-circle-thin', 'icon_on': 'fa-circle'}, 'fields': {'units': '%', 'state_text': '', 'title2': '', 'level': '', 'icon_style': '', 'title': 'Kitchen Strip', 'icon': ''}, 'widget_type': 'baselight', 'static_css': {'level_up_style': 'color: #888;', 'level_style': 'color: #fff;', 'widget_style': 'background-color: #444;', 'level_down_style': 'color: #888;', 'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'state_text_style': 'color: #fff;'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.kitchen_strip'}, 'use_hass_icon': 1, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}})
    
        widgets["default-sync-kitchen-strip"] = new baseswitch("default-sync-kitchen-strip", "http://dk.servebeer.com:5050", "default", {'use_comma': 0, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'input_boolean.kitchen_strip_on'}, 'state_active': 'on', 'enable': 1, 'entity': 'input_boolean.kitchen_strip_on', 'precision': 1, 'css': {'icon_style_inactive': 'color: #888;', 'icon_style_active': 'color: #aaff00;'}, 'icons': {'icon_off': 'fa-sliders', 'icon_on': 'fa-sliders'}, 'fields': {'icon_style': '', 'state_text': '', 'title2': '', 'title': 'Is Kitchen Strip On', 'icon': ''}, 'widget_type': 'baseswitch', 'state_inactive': 'off', 'static_css': {'widget_style': 'background-color: #444;', 'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'input_boolean.kitchen_strip_on'}, 'use_hass_icon': 1, 'static_icons': []})
    
        widgets["default-shop"] = new baselight("default-shop", "http://dk.servebeer.com:5050", "default", {'use_comma': 0, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'group.shop'}, 'css': {'icon_style_inactive': 'color: #888;', 'icon_style_active': 'color: #aaff00;'}, 'entity': 'group.shop', 'precision': 1, 'icons': {'icon_off': 'mdi-wrench', 'icon_on': 'mdi-wrench'}, 'static_css': {'level_up_style': 'color: #888;', 'level_style': 'color: #fff;', 'widget_style': 'background-color: #444;', 'level_down_style': 'color: #888;', 'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'state_text_style': 'color: #fff;'}, 'fields': {'units': '%', 'state_text': '', 'title2': '', 'level': '', 'icon_style': '', 'title': 'Shop', 'icon': ''}, 'widget_type': 'baselight', 'icon_off': 'mdi-wrench', 'icon_on': 'mdi-wrench', 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'group.shop'}, 'use_hass_icon': 1, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}})
    
        widgets["default-bedroom"] = new baselight("default-bedroom", "http://dk.servebeer.com:5050", "default", {'use_comma': 0, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'group.bedroom'}, 'css': {'icon_style_inactive': 'color: #888;', 'icon_style_active': 'color: #aaff00;'}, 'entity': 'group.bedroom', 'precision': 1, 'icons': {'icon_off': 'mdi-hotel', 'icon_on': 'mdi-hotel'}, 'static_css': {'level_up_style': 'color: #888;', 'level_style': 'color: #fff;', 'widget_style': 'background-color: #444;', 'level_down_style': 'color: #888;', 'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'state_text_style': 'color: #fff;'}, 'fields': {'units': '%', 'state_text': '', 'title2': '', 'level': '', 'icon_style': '', 'title': 'Bedroom', 'icon': ''}, 'widget_type': 'baselight', 'icon_off': 'mdi-hotel', 'icon_on': 'mdi-hotel', 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'group.bedroom'}, 'use_hass_icon': 1, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}})
    
        widgets["default-theater-scene"] = new baseswitch("default-theater-scene", "http://dk.servebeer.com:5050", "default", {'ignore_state': 1, 'use_comma': 0, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'scene.theater'}, 'state_active': 'stillscening', 'css': {'icon_style_inactive': 'color: #888;', 'icon_style_active': 'color: #aaff00;'}, 'entity': 'scene.theater', 'precision': 1, 'title_style': 'color: #922B21;font-weight:bold;', 'static_icons': [], 'momentary': 1000, 'enable': 1, 'icons': {'icon_off': 'mdi-movie', 'icon_on': 'mdi-movie'}, 'static_css': {'widget_style': 'background-color: #E59866;', 'title_style': 'color: #922B21;font-weight:bold;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;'}, 'fields': {'icon_style': '', 'state_text': '', 'title2': '', 'title': 'Theater Mode', 'icon': ''}, 'widget_type': 'baseswitch', 'icon_off': 'mdi-movie', 'state_inactive': 'scening', 'icon_on': 'mdi-movie', 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'scene.theater'}, 'use_hass_icon': 1, 'widget_style': 'background-color: #E59866;'})
    
        widgets["default-warm-scene"] = new baseswitch("default-warm-scene", "http://dk.servebeer.com:5050", "default", {'ignore_state': 1, 'use_comma': 0, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'scene.warm'}, 'state_active': 'stillscening', 'css': {'icon_style_inactive': 'color: #888;', 'icon_style_active': 'color: #aaff00;'}, 'entity': 'scene.warm', 'precision': 1, 'title_style': 'color: #D35400;font-weight:bold;', 'static_icons': [], 'momentary': 1000, 'enable': 1, 'icons': {'icon_off': 'mdi-weather-sunset', 'icon_on': 'mdi-weather-sunset'}, 'static_css': {'widget_style': 'background-color: #F7DC6F;', 'title_style': 'color: #D35400;font-weight:bold;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;'}, 'fields': {'icon_style': '', 'state_text': '', 'title2': '', 'title': 'Warm', 'icon': ''}, 'widget_type': 'baseswitch', 'icon_off': 'mdi-weather-sunset', 'state_inactive': 'scening', 'icon_on': 'mdi-weather-sunset', 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'scene.warm'}, 'use_hass_icon': 1, 'widget_style': 'background-color: #F7DC6F;'})
    
        widgets["default-label-state"] = new basedisplay("default-label-state", "http://dk.servebeer.com:5050", "default", {'css': {}, 'icons': [], 'use_comma': 0, 'fields': {'value': 'States', 'unit': '', 'state_text': '', 'title2': '', 'title': ''}, 'widget_type': 'basedisplay', 'precision': 1, 'static_icons': [], 'use_hass_icon': 1, 'static_css': {'widget_style': 'background-color: #444;', 'unit_style': '', 'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'value_style': 'color: #fff;'}})
    

    // Setup click handler to cancel timeout navigations

    $( ".gridster" ).click(function(){
        clearTimeout(myTimeout);
    });

    // Set up timeout

    var myTimeout

    if (location.search != "")
    {
        var query = location.search.substr(1);
        var result = {};
        query.split("&").forEach(function(part) {
        var item = part.split("=");
        result[item[0]] = decodeURIComponent(item[1]);
        });

        if ("timeout" in result && "return" in result)
        {
            url = result.return
            argcount = 0
            for (arg in result)
            {
                if (arg != "timeout" && arg != "return")
                {
                    if (argcount == 0)
                    {
                        url += "?";
                    }
                    else
                    {
                        url += "?";
                    }
                    argcount ++;
                    url += arg + "=" + result[arg]
                }
            }
            myTimeout = setTimeout(function() { navigate(url); }, result.timeout * 1000);
        }
    }

    // Start listening for HA Events
    if (location.protocol == 'https:')
    {
        wsprot = "wss:"
    }
    else
    {
        wsprot = "ws:"
    }
    var stream_url = wsprot + '//' + location.host + '/stream'
    ha_status(stream_url, "Main Panel", widgets);

});