alias: "Christine entering house after being outside"
trigger:
  platform: state
  entity_id: sensor.front_door
  to: 'OFF'
condition:
  - condition: state
    entity_id: input_select.home_state
    state: Inside
  - condition: state
    entity_id: input_select.christine_home_state
    state: Outside
action:
  - service: scene.turn_on
    entity_id: scene.red
  - service: input_select.select_option
    data:
      entity_id: input_select.christine_home_state
      option: Entering
