alias: "Christine just arrived in home zone and is outside"
trigger:
  platform: state
  entity_id: device_tracker.donkawechico_sailfish
  from: 'not_home'
  to: 'home'
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.christine_home_state
      option: Outside
