- alias: "Enable light-related automations when someone is home"
  trigger:
    platform: state
    entity_id: input_boolean.someone_home
    to: 'on'
  action:
    - service: automation.turn_on
      entity_id: group.automations_to_turn_off_when_no_one_home
- alias: "Disable light-related automations when no one is home"
  trigger:
    platform: state
    entity_id: input_boolean.someone_home
    to: 'off'
  action:
    - service: automation.turn_off
      entity_id: group.automations_to_turn_off_when_no_one_home
