- alias: "Enable light-related automations"
  trigger:
    platform: state
    entity_id: binary_sensor.dark_out
    to: 'on'
  action:
    - service: automation.turn_on
      entity_id: group.automations_to_turn_off_when_dark
- alias: "Disable light-related automations"
  trigger:
    platform: state
    entity_id: binary_sensor.dark_out
    to: 'off'
  action:
    - service: automation.turn_off
      entity_id: group.automations_to_turn_off_when_dark
