- alias: "Enable bedtime-related automations"
  trigger:
    platform: state
    entity_id: input_select.house_mode
    to: 'Bedtime'
  action:
    - service: automation.turn_on
      entity_id: group.automations_to_turn_on_when_bedtime
- alias: "Disable bedtime-related automations"
  trigger:
  - platform: state
    entity_id: binary_sensor.dark_out
    to: 'off'
  - platform: state
    entity_id: input_select.house_mode
    from: 'bedtime'
  action:
    - service: automation.turn_off
      entity_id: group.automations_to_turn_on_when_bedtime
